
version: '02'
services:
  mysql:
    ports:
      - "3306:3306"
    build:
      context: .
      dockerfile: m_docker/Dockerfile
    image: mysql:latest
    container_name: my-mysql-container
    #    environment:
    #  - MYSQL_ROOT_PASSWORD=1234
    networks:
      - my-network

  apache-php:
    build:
      context: .
      dockerfile: a_docker/Dockerfile
    image: php:7.4-apache
    container_name: my-apache-php-container
    ports:
      - 85:80
    networks:
      - my-network
    depends_on:
      - mysql

networks:
  my-network:
